### ISSUE TITLE
Get All Widget Templates channel_id query param has no effect.

### ISSUE THREAD

**Issue by tomzweb** [bigcommerce/api-specs#819] opened 2022-06-14 13:44 UTC
According to the docs: https://developer.bigcommerce.com/api-reference/15b810ee7c012-get-all-widget-templates - channel_id should filter the results by the provided channel_id. However, nothing is filtered. 

Using the query param "channel_id:in" works.

Not sure if the docs need changing, or whether the API needs amending to work in the way the docs describe.

**Comment by slsriehl** [comment] 2022-06-14 16:46
Thanks @tomzweb. We'll update the spec. The API is working as intended.

DEVDOCS-4210

**Comment by slsriehl** [comment] 2023-06-09 21:11
Addressed in the following PRs:
* #897 
* #926 

Thanks for your contributing issue!

**Closed by slsriehl** 2023-06-09 21:11 UTC
