### ISSUE TITLE
Customer V3 names

### ISSUE THREAD

**Issue by stevenbrookes** [bigcommerce/api-specs#1030] opened 2022-10-31 12:25 UTC
In the customer_Full model first_name and last_name have min length 1.  However we've seen API responses with a length of 0, which then can't be de-serialised.  Can you change the limits

        first_name:
          description: The first name of the customer.
          type: string
          minLength: 1
          maxLength: 100
        last_name:
          description: The last name of the customer.
          type: string
          minLength: 1
          maxLength: 100

to

        first_name:
          description: The first name of the customer.
          type: string
          minLength: 0
          maxLength: 100
        last_name:
          description: The last name of the customer.
          type: string
          minLength: 0
          maxLength: 100

**Comment by bc-traciporter** [comment] 2022-10-31 16:50
@stevenbrookes thanks for bringing this to our attention. Can you explain how it is possible to have 0 minLength?

**Comment by stevenbrookes** [comment] 2022-11-02 09:20
Well all I know is on one of the BC instances we are connected to via the API we are seeing sales where the customer first name and last name are zero length. Seems odd I agree, but that's what we see.  I don't have any insight into why that's happening in BC as we are a 3rd part just providing integration services.

**Comment by dougep** [comment] 2022-11-10 07:00
Hi @stevenbrookes, would you be able to provide some examples of API queries and responses where you see zero length please? That's not something that should be allowed, so a couple of examples would help us to dig a bit deeper. Please include the store and customer IDs, query url and result payload. Thanks.

**Comment by stevenbrookes** [comment] 2022-11-10 09:08
OK I managed to pull an example from our logging system.  Call was

https://api.bigcommerce.com/stores/lh9wfk05w0/v3/customers?id%3Ain=10527",

Response was

 "X-Request-ID": "60be554500d1d71cb3971d9ce3f47979",


{
    "data": [
      {
        "id": 10527,
        "authentication": {
          "force_password_reset": false
        },
        "company": "",
        "customer_group_id": 0,
        "email": "catherinerea@doctors.org.uk",
        "first_name": "",
        "last_name": "",
        "notes": "",
        "phone": "Catherine",
        "registration_ip_address": "",
        "tax_exempt_category": "",
        "date_created": "2022-08-23T11:52:23Z",
        "date_modified": "2022-08-23T11:52:23Z",
        "accepts_product_review_abandoned_cart_emails": true,
        "origin_channel_id": 1,
        "channel_ids": null
      }
    ],
    "meta": {
      "pagination": {
        "total": 1,
        "count": 1,
        "per_page": 50,
        "current_page": 1,
        "total_pages": 1
      }
    }
  }

Hope that helps.  I locally patched the swagger file so I don't see the error now, so finding another example won't be so easy.

**Comment by slsriehl** [comment] 2023-06-09 21:26
Thanks for engaging, @stevenbrookes. From a docs perspective, I've confirmed that this is not the intended behavior, so I'm going to close this issue out.

For a connection to more BigCommerce developer resources, consider engaging in our [Developer Community](https://developer.bigcommerce.com/community).

**Closed by slsriehl** 2023-06-09 21:26 UTC

**Comment by stevenbrookes** [comment] 2023-06-12 07:43
When you say you're are "going to close this out", have you fixed the issue in the OpenAPI file? BC is able to create a message that's not compliant with the OpenAPI file, so either the OpenAPI file or BC needs updating to bring them in line with each other.  I've provided a concrete example of this above as requested.
